baseURL = 'https://cegepmv.github.io/420-313/'
locale = 'fr-ca'
title = 'SÉCURITÉ INFORMATIQUE'
theme = 'hugo-theme-relearn'
enableEmoji = true

[params]
  disableLandingPageButton = true
  themeVariant = ['zen-dark', 'zen-light']
  [params.logo]
    src = '/images/logo.png'
    direction = 'row'
  [params.search]
    disable = true
    [params.search.index]
      disable = true

    [params.search.page]
      disable = true
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'